POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="aaa.mp4"
Content-Type: video/mp4

< ./aaa.mp4

------FormBoundary1234

### POST - zdjecia
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NTk1MDIzNjc2MCwiaWF0IjoxNjg1OTUwMjQ1LCJleHAiOjE2ODg1NDIyNDV9.FvKDG-tUeQfndmmNOJPGXRZqfg0z6QnuR8IkPwk81Uk

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpg

< ./test.jpg

------FormBoundary1234

### GET
GET http://localhost:3000/api/photos HTTP/1.1

### GET
GET http://localhost:3000/api/photos/image/1685950278975 HTTP/1.1

### PATCH - updatuj wg id
PATCH  http://localhost:3000/api/photos HTTP/1.1
content-type: application/json

{
    "id": 1682324386683,
    "status":"change"
}
### PATCH - tags
PATCH  http://localhost:3000/api/photos/tags HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NTg3NTIyMjU4NiwiaWF0IjoxNjg1ODc1MjI5LCJleHAiOjE2ODg0NjcyMjl9.EAiENDrunIUm6yEzwfNsRlXoTmKS2LoqhS5zqnDrtqA

{
    "id": 1685875250263,
    "tags":[
        {"id":10},
        {"id":12},
        {"id":1}
    ]
}


### DELETE
DELETE http://localhost:3000/api/photos/1685878481493
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NTg3NTIyMjU4NiwiaWF0IjoxNjg1ODc1MjI5LCJleHAiOjE2ODg0NjcyMjl9.EAiENDrunIUm6yEzwfNsRlXoTmKS2LoqhS5zqnDrtqA