### POST
POST http://localhost:3000/api/user/register HTTP/1.1

{
    "name":"Mateusz",
    "lastname":"Stoch",
    "email":"aab@gmail.com",
    "passwd":"aaabbbccc"
}
### POST
POST http://localhost:3000/api/user/login HTTP/1.1

{
    "email":"aab@gmail.com",
    "passwd":"aaabbbccc"
}

###GET

GET http://localhost:3000/api/user
