### POST
POST http://localhost:3000/api/user/register HTTP/1.1

{
    "name":"Mateusz",
    "lastname":"Stoch",
    "email":"aab@gmail.com",
    "passwd":"aaabbbccc"
}
### POST
POST http://localhost:3000/api/user/login HTTP/1.1

{
    "email":"aab@gmail.com",
    "passwd":"aaabbbccc"
}

###GET

GET http://localhost:3000/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NTg3ODU1MTc5MSwiaWF0IjoxNjg1ODc4NTY2LCJleHAiOjE2ODg0NzA1NjZ9.RiCRhdBFG4auwHc96TQKC-PTiawDeU7C0ee6eZmF7tU
